name: Automated tests for Python using Pytest

on:
  push:
    branches:
      - master
      - feature-*
  pull_request:
    branches:
      - master
      - feature-*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install software
      run: |
        sudo apt-get install -y chromium-browser

    - name: Set Environment Variables from Secrets
      run: |
        echo "NEWS_PAGE_URL=${{ secrets.NEWS_PAGE_URL }}" >> $GITHUB_ENV
        echo "ALPHA_VANTAGE_API_KEY=${{ secrets.ALPHA_VANTAGE_API_KEY }}" >> $GITHUB_ENV
        echo "ALPHA_VANTAGE_URL=${{ secrets.ALPHA_VANTAGE_URL }}" >> $GITHUB_ENV

    - name: Run tests
      run: pytest -v